export const ADD_RECIPE = "ADD_RECIPE";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const EDIT_INGREDIENT = "EDIT_INGREDIENT";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
